modLoader="javafml"
loaderVersion="$fmlrange"
license="$license"
issueTrackerURL="https://github.com/${github}/issues"

[[mods]]
    modId="$modid"
    version="$modversion"
    displayName="$modname"
    displayTest="MATCH_VERSION"
    logoFile="pack.png"
    authors="$modauthors"
    credits="$modcredits"
    description='''$moddesc'''

[[dependencies.$modid]]
    modId="watermedia"
    mandatory=true
    versionRange="$watermediarange"
    ordering="AFTER"
    side="CLIENT"

[[dependencies.${modid}]]
    modId="minecraft"
    mandatory=true
    # This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="${minecraftversion}"
    ordering="NONE"
    side="BOTH"